### ISSUE TITLE
Questions Reg This script

### ISSUE THREAD

**Issue by varunsridharan** [peter279k/mirror-kickstarter#3]
Hello There
Thanks for creating this utility. i have followed all the steps in your readme.md

and my current config file looks like below

```php
return [
    'target_dir' => __DIR__.'/public/',
    'user_agent' => '',
    'repo_url' => 'https://repo.packagist.org',
    'api_url' => 'https://packagist.org',
    'iterations' => 120,
    'iteration_interval' => 5,
    'has_v1_mirror' => true,
];

```

and everything is configured as per the readme.md but i am not sure how often this script syncs ? like very 1 hrs or ?

**Comment by peter279k** [comment]
Hi @varunsridharan, thanks for your reply.

The frequent mirroring script syncing is for any time. that's the reason why syncing mirror script is managed by supervisor service :).

And you can look at the [mirror.php](https://github.com/composer/mirror/blob/master/mirror.php#L795) file, it will sleep 3 seconds if the syncing mirror script has been failed :).

**Comment by varunsridharan** [comment]
> Hi @varunsridharan, thanks for your reply.
> 
> The frequent mirroring script syncing is for any time. that's the reason why syncing mirror script is managed by supervisor service :).
> 
> And you can look at the [mirror.php](https://github.com/composer/mirror/blob/master/mirror.php#L795) file, it will sleep 3 seconds if the syncing mirror script has been failed :).

Hi

So that means this script is always syncing right ?

**Comment by peter279k** [comment]
Yes. It will always run syncing script at normal situation.

**Comment by varunsridharan** [comment]
@peter279k thanks for the response but its still not clear if my setup is syncing the files

So to identify it i edited the `mirror.php` (https://github.com/composer/mirror/blob/master/mirror.php)

and updated the function
```php
    private function writeLastTimestamp(int $timestamp)
    {
        if (false === file_put_contents($this->getTimestampStorePath(), $timestamp)) {
            throw new \UnexpectedValueException('Could not save last timestamp to last_metadata_timestamp in '.getcwd().'. Make sure the file/directory is writable');
        }
    }
```

with the below line

```diff
    private function writeLastTimestamp(int $timestamp)
    {
+       file_put_contents('./last_updated',time());
        if (false === file_put_contents($this->getTimestampStorePath(), $timestamp)) {
            throw new \UnexpectedValueException('Could not save last timestamp to last_metadata_timestamp in '.getcwd().'. Make sure the file/directory is writable');
        }
    }
```

and it seems that the sync is not working because the timestamp in the file `last_updated` is not changed since my last manual run.

My mirror web url is : https://packagist.in/

**Comment by peter279k** [comment]
@varunsridharan, thanks for your reply.

IMHO, I think you don't have to modify the `mirror.php` for that. And the `mirror.php` is maintained by the official Composer.

I just setup the Composer mirror kick starter quickly, not modifying the `mirror.php` :).

**Comment by peter279k** [comment]
BTW, if you want to ensure the mirror is syncing, you should check the last modified time of meta data files generated by `Composer Mirror` script.

![圖片](https://user-images.githubusercontent.com/9021747/103859890-c9560700-50f5-11eb-8d97-da3e84c1822f.png)
